### ISSUE TITLE
Testing: Testing with Windows 11, 8.1, 8

### ISSUE THREAD

**Issue by suhaskv1** [acmpesuecc/ResourcePolice#5]
## Description
Test with other versions of Windows versions and report back with a fairly articulate document of your findings. Attach the document and wait for confirmation from the maintainers.

## Prefered Implementation
Things to be noted
- Do not forget to mention the versions and build numbers of Windows that you are testing.
- If you can provide and implement a fix for issues caused in the other versions, you will be awarded brownie points!

## Resources
Refer to this stack [post](https://stackoverflow.com/questions/32781997/test-my-program-in-different-windows-versions) to learn more about multiple OS testing.

**Bounty points allotted: 100+**

If you face any issues or have any queries, do not hesitate to contact the maintainers. Happy contributing!

**Comment by NandanHemanth** [comment]
Can you please assign this to me

**Comment by suhaskv1** [comment]
@NandanHemanth assigned!
