### ISSUE TITLE
Feature request: Implement the same program to work with Linux.

### ISSUE THREAD

**Issue by suhaskv1** [acmpesuecc/ResourcePolice#6]
## Description
Try to port this program and make changes to it to make it work with Linux. This is a hard task and is valid for brownie points.

## Prefered Implementation
Find other alternatives to the **win10toast** library for Linux and/or macOS. Keep the code simple and clean. 

Things to note
- Follow the same style of coding as the original code.
- Do keep an eye out for the other two issues #3 and #4 and implement those as well to be awarded brownie points.
- Comments are a requirement here.

## Resources
Refer to this [link](https://pypi.org/project/inappropriate-notifications/) to learn more about the alternative to win10toast.

**Bounty points allotted: 100+**

If you face any issues or have any queries, do not hesitate to contact the maintainers. Happy contributing!

**Comment by PhoenixFlame101** [comment]
Hey can I be assigned this issue?

**Comment by suhaskv1** [comment]
Also, @PhoenixFlame101 text on discord if you have any queries.

**Comment by RakshithRAcharya** [comment]
Hey @Noel-Saju for This can I combine #3 in the same PR or should I do it seperately

**Comment by Noel-Saju** [comment]
> Could I be assigned to this issue?

you've been assigned
